### ISSUE TITLE
Create user notification sent twice

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/lambda2sns#15]
# The problem:

- Create a new user via the Unee-T enterprise interface - PASSED
- Send the lambda notification to - PASSED
- Send the AWS SNS notification - PASSED with issue: the AWS message seems to be sent twice

See that payload for an example of the issue
```
{"lastName": "test user", "creatorId": "E4RFHFCQGsXGPcCb5", "firstName": "Help", "actionType": "CREATE_USER", "phoneNumber": "", "emailAddress": "email.catcher+default.assignee.mgtCny@unee-t.com", "userCreationRequestId": 37}
```

**Comment by kaihendry** [comment]
Which environment?

**Comment by kaihendry** [comment]
I think I've debugged the problem: https://media.dev.unee-t.com/2019-04-25/duplicate-message.mp4

cc @nbiton you need to track internal server errors in Meteor. I don't know why it gave that response and then on retry "Duplicate message". Or perhaps return 200 instead of **400** as you currently do for duplicate message?
